# This is a basic workflow to help you get started with Actions

name: Deploy on Github Pages

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.x' # you can use 1.12
          channel: 'beta' # Currently you have to use beta channel for Flutter web.
      - name: Upgrades flutter
        run: flutter upgrade
        working-directory: ./example
      - name: Enable Web
        run: flutter config --enable-web
        working-directory: ./example
      - name: Install dependencies
        run: flutter packages get
        working-directory: ./example
      - name: Build Web
        run: flutter build web
        working-directory: ./example
      - name: Deploy
        run: |
          cd example/build/web
          git init
          git config user.name  "CI"
          git config user.email "flutter-ci@github.com"
          git remote add secure-origin https://${{ secrets.NEOLATINO_TOKEN }}@github.com/neolatino/dictionario.git
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy new version"
          git push --force secure-origin gh-pages
